dist: bionic
language: php


matrix:
    fast_finish: true
    include:
        - php: 7.2
        - php: 7.3
        - php: 7.4

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update

install:
    - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
