name: "Laravel 8"

on: [ push, pull_request ]

permissions: read-all

jobs:
    laravel:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "8.1" ]
                laravel: [ "8.0" ]
                prefer: [ "stable", "lowest" ]

        name: PHP ${{ matrix.php }} ${{ matrix.prefer }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Install dependencies
                run: composer require laravel/framework:^${{ matrix.laravel }} --prefer-${{ matrix.prefer }}

            -   name: Execute tests
                run: sudo vendor/bin/phpunit
