name: phpunit
on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [7.2, 7.3, 7.4]
                laravel: [6.*, 7.*]

        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug

            -   name: Composer self update
                run: |
                    composer self-update
                    composer global require hirak/prestissimo --no-plugins

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Install dependencies
                run: composer update --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest

            -   name: Execute tests
                run: |
                    mkdir -p build/logs
                    vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

            -   name: Scrutinizer CI
                run: |
                    wget https://scrutinizer-ci.com/ocular.phar
                    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
